name: CMake CI

on:
  push:
    branches:
      - main
  pull request:
    branches:
      - main

jobs:
  build:
    runs-on ubuntu-latest

    steps:

      -name: Chekout repository

      uses: actions/chekout@v2


      -name: Set Up CMake
      
      uses: actions/setup-cmake@v2


      -name: Configure CMake

      run: cmake .


      -name: Build

      run: cmake --build


      -name: Run tests

      run: cmake --build , --target test 